import { InsertSacredMatrixEntry } from "@shared/schema";

// Biblical Matrix data parsed from CSV  
export const sacredMatrixData: InsertSacredMatrixEntry[] = [
  {
    chapterNumber: 1,
    bookNumber: 1,
    divineName: "Yod",
    bookName: "Becoming Rooted",
    bookTheme: "Identity, Calling, and the Formation of Glory",
    chapterTitle: "Leadership Begins at the Altar",
    geometryIcon: "Square",
    stone: "Sardius",
    element: "Fire",
    templeSpace: "Altar",
    storyStage: "Exposition",
    dimension: "1 Glory",
    fractalGate: "Revelation",
    spiritualFrequency: "Deep Stillness",
    bookColor: "Red",
    tribe: "Reuben",
    prophet: "Hosea",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 2,
    bookNumber: 1,
    divineName: "Yod",
    bookName: "Becoming Rooted",
    bookTheme: "Identity, Calling, and the Formation of Glory",
    chapterTitle: "The Tripartite Leader: Spirit, Soul, and Body",
    geometryIcon: "Equilateral Triangle",
    stone: "Topaz",
    element: "Fire",
    templeSpace: "Altar",
    storyStage: "Rising Action",
    dimension: "6 Image",
    fractalGate: "Internalization",
    spiritualFrequency: "Triune Tone",
    bookColor: "Red",
    tribe: "Simeon",
    prophet: "Joel",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 3,
    bookNumber: 1,
    divineName: "Yod",
    bookName: "Becoming Rooted",
    bookTheme: "Identity, Calling, and the Formation of Glory",
    chapterTitle: "Why We Had to Leave Eden",
    geometryIcon: "2D Spiral",
    stone: "Emerald",
    element: "Fire",
    templeSpace: "Altar",
    storyStage: "Climax",
    dimension: "2 Presence",
    fractalGate: "Embodiment",
    spiritualFrequency: "Exilic Echo",
    bookColor: "Red",
    tribe: "Levi",
    prophet: "Amos",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 4,
    bookNumber: 1,
    divineName: "Yod",
    bookName: "Becoming Rooted",
    bookTheme: "Identity, Calling, and the Formation of Glory",
    chapterTitle: "Formation in Exile: The Purpose of the Fall",
    geometryIcon: "Isometric Cube",
    stone: "Carbuncle",
    element: "Fire",
    templeSpace: "Altar",
    storyStage: "Falling Action",
    dimension: "4 Word",
    fractalGate: "Integration",
    spiritualFrequency: "Structure Hum",
    bookColor: "Red",
    tribe: "Judah",
    prophet: "Obadiah",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 5,
    bookNumber: 1,
    divineName: "Yod",
    bookName: "Becoming Rooted",
    bookTheme: "Identity, Calling, and the Formation of Glory",
    chapterTitle: "The Seed Hidden in the Dust",
    geometryIcon: "Monad Unity Point",
    stone: "Onyx",
    element: "Fire",
    templeSpace: "Altar",
    storyStage: "Resolution",
    dimension: "7 Name",
    fractalGate: "Hidden (North)",
    spiritualFrequency: "Subterranean Hum",
    bookColor: "Red",
    tribe: "Dan",
    prophet: "Jonah",
    apostle: null,
    directionalMapping: "North",
  },
  {
    chapterNumber: 6,
    bookNumber: 2,
    divineName: "Heh",
    bookName: "Becoming Aligned",
    bookTheme: "Patterns and the Spiritual Core of Leadership",
    chapterTitle: "Jesus as the Tree of Life, the Flaming Sword, and the Cosmic Unifier",
    geometryIcon: "Tetrahedron + Rays",
    stone: "Sapphire",
    element: "Air",
    templeSpace: "Holy Place",
    storyStage: "Exposition",
    dimension: "6 Image",
    fractalGate: "Revelation",
    spiritualFrequency: "Tree Flame Pulse",
    bookColor: "Blue",
    tribe: "Naphtali",
    prophet: "Micah",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 7,
    bookNumber: 2,
    divineName: "Heh",
    bookName: "Becoming Aligned",
    bookTheme: "Patterns and the Spiritual Core of Leadership",
    chapterTitle: "The Divine Pattern: YHWH Structure and the Wings of Wisdom",
    geometryIcon: "Hexagonal Mandala",
    stone: "Diamond",
    element: "Air",
    templeSpace: "Holy Place",
    storyStage: "Rising Action",
    dimension: "4 Word",
    fractalGate: "Internalization",
    spiritualFrequency: "Wings of Wisdom Vibration",
    bookColor: "Blue",
    tribe: "Gad",
    prophet: "Nahum",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 8,
    bookNumber: 2,
    divineName: "Heh",
    bookName: "Becoming Aligned",
    bookTheme: "Patterns and the Spiritual Core of Leadership",
    chapterTitle: "The Pattern Keeper: Heaven Interface and Leadership Design",
    geometryIcon: "Octahedron",
    stone: "Ligure",
    element: "Air",
    templeSpace: "Holy Place",
    storyStage: "Climax",
    dimension: "2 Presence",
    fractalGate: "Embodiment",
    spiritualFrequency: "Guardian Harmonic",
    bookColor: "Blue",
    tribe: "Asher",
    prophet: "Habakkuk",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 9,
    bookNumber: 2,
    divineName: "Heh",
    bookName: "Becoming Aligned",
    bookTheme: "Patterns and the Spiritual Core of Leadership",
    chapterTitle: "The Fractal Pattern of Leadership",
    geometryIcon: "Fibonacci Spiral",
    stone: "Agate",
    element: "Air",
    templeSpace: "Holy Place",
    storyStage: "Falling Action",
    dimension: "5 Spirit",
    fractalGate: "Integration",
    spiritualFrequency: "Recursive Tone",
    bookColor: "Blue",
    tribe: "Issachar",
    prophet: "Zephaniah",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 10,
    bookNumber: 2,
    divineName: "Heh",
    bookName: "Becoming Aligned",
    bookTheme: "Patterns and the Spiritual Core of Leadership",
    chapterTitle: "The Invisible Root System of Authority",
    geometryIcon: "Fractal Tree",
    stone: "Amethyst",
    element: "Air",
    templeSpace: "Holy Place",
    storyStage: "Resolution",
    dimension: "7 Name",
    fractalGate: "Hidden (South)",
    spiritualFrequency: "Root Resonance",
    bookColor: "Blue",
    tribe: "Zebulun",
    prophet: "Haggai",
    apostle: null,
    directionalMapping: "South",
  },
  {
    chapterNumber: 11,
    bookNumber: 3,
    divineName: "Vav",
    bookName: "Becoming Clear",
    bookTheme: "Vision, Emotional Intelligence, and the Inner Compass",
    chapterTitle: "Vision of God: The First Call of Every Leader",
    geometryIcon: "Icosahedron",
    stone: "Beryl",
    element: "Water",
    templeSpace: "Inner Light",
    storyStage: "Exposition",
    dimension: "1 Glory",
    fractalGate: "Revelation",
    spiritualFrequency: "Visionary Call",
    bookColor: "Teal",
    tribe: "Joseph (Ephraim)",
    prophet: "Zechariah",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 12,
    bookNumber: 3,
    divineName: "Vav",
    bookName: "Becoming Clear",
    bookTheme: "Vision, Emotional Intelligence, and the Inner Compass",
    chapterTitle: "Vision of Self: Emotional Tools and Soul Awareness",
    geometryIcon: "Hexagonal Prism",
    stone: "Onyx (2)",
    element: "Water",
    templeSpace: "Inner Light",
    storyStage: "Rising Action",
    dimension: "3 Voice",
    fractalGate: "Internalization",
    spiritualFrequency: "Soul Frequency",
    bookColor: "Teal",
    tribe: "Benjamin",
    prophet: "Malachi",
    apostle: null,
    directionalMapping: null,
  },
  {
    chapterNumber: 13,
    bookNumber: 3,
    divineName: "Vav",
    bookName: "Becoming Clear",
    bookTheme: "Vision, Emotional Intelligence, and the Inner Compass",
    chapterTitle: "Vision of Mission: Discovering Your Divine Measure",
    geometryIcon: "Golden Ratio Spiral",
    stone: "Jasper",
    element: "Water",
    templeSpace: "Inner Light",
    storyStage: "Climax",
    dimension: "4 Word",
    fractalGate: "Embodiment",
    spiritualFrequency: "Mission Tuning",
    bookColor: "Teal",
    tribe: null,
    prophet: "John the Baptist",
    apostle: "Peter",
    directionalMapping: null,
  },
  {
    chapterNumber: 14,
    bookNumber: 3,
    divineName: "Vav",
    bookName: "Becoming Clear",
    bookTheme: "Vision, Emotional Intelligence, and the Inner Compass",
    chapterTitle: "The Wounded Visionary: Leading Through Inner Conflict",
    geometryIcon: "Mobius Strip",
    stone: "Sapphire",
    element: "Water",
    templeSpace: "Inner Light",
    storyStage: "Falling Action",
    dimension: "6 Image",
    fractalGate: "Integration",
    spiritualFrequency: "Wounded Harmony",
    bookColor: "Teal",
    tribe: null,
    prophet: "Elijah",
    apostle: "James (Zebedee)",
    directionalMapping: null,
  },
  {
    chapterNumber: 15,
    bookNumber: 3,
    divineName: "Vav",
    bookName: "Becoming Clear",
    bookTheme: "Vision, Emotional Intelligence, and the Inner Compass",
    chapterTitle: "Sacred Sight: From Revelation to Discernment",
    geometryIcon: "Metatron Cube",
    stone: "Chalcedony",
    element: "Water",
    templeSpace: "Inner Light",
    storyStage: "Resolution",
    dimension: "7 Name",
    fractalGate: "Hidden (East)",
    spiritualFrequency: "Sight Pulse",
    bookColor: "Teal",
    tribe: null,
    prophet: "John the Revelator",
    apostle: "John",
    directionalMapping: "East",
  },
  {
    chapterNumber: 16,
    bookNumber: 4,
    divineName: "Final Heh",
    bookName: "Becoming Embodied",
    bookTheme: "Walking in Wisdom, Spirit, and Glory",
    chapterTitle: "Emotional Intelligence and Passion",
    geometryIcon: "3D Pentagon",
    stone: "Emerald (2)",
    element: "Earth",
    templeSpace: "Holy of Holies",
    storyStage: "Exposition",
    dimension: "5 Spirit",
    fractalGate: "Revelation",
    spiritualFrequency: "Passion Current",
    bookColor: "Green",
    tribe: null,
    prophet: "Samuel",
    apostle: "Andrew",
    directionalMapping: null,
  },
  {
    chapterNumber: 17,
    bookNumber: 4,
    divineName: "Final Heh",
    bookName: "Becoming Embodied",
    bookTheme: "Walking in Wisdom, Spirit, and Glory",
    chapterTitle: "Intelligent Action: Decision-Making in Alignment with the Spirit",
    geometryIcon: "Tetrahedron",
    stone: "Sardonyx",
    element: "Earth",
    templeSpace: "Holy of Holies",
    storyStage: "Rising Action",
    dimension: "4 Word",
    fractalGate: "Internalization",
    spiritualFrequency: "Aligned Decision Pulse",
    bookColor: "Green",
    tribe: null,
    prophet: "Nathan",
    apostle: "Philip",
    directionalMapping: null,
  },
  {
    chapterNumber: 18,
    bookNumber: 4,
    divineName: "Final Heh",
    bookName: "Becoming Embodied",
    bookTheme: "Walking in Wisdom, Spirit, and Glory",
    chapterTitle: "Embodied Leadership: Why Your Body Matters",
    geometryIcon: "Isometric Grid",
    stone: "Carnelian",
    element: "Earth",
    templeSpace: "Holy of Holies",
    storyStage: "Climax",
    dimension: "6 Image",
    fractalGate: "Embodiment",
    spiritualFrequency: "Embodied Presence",
    bookColor: "Green",
    tribe: null,
    prophet: "Gad",
    apostle: "Bartholomew",
    directionalMapping: null,
  },
  {
    chapterNumber: 19,
    bookNumber: 4,
    divineName: "Final Heh",
    bookName: "Becoming Embodied",
    bookTheme: "Walking in Wisdom, Spirit, and Glory",
    chapterTitle: "Mentors and Mirrors: Leading Like Jesus in a Fractured World",
    geometryIcon: "Reflection Diagram",
    stone: "Chrysolite",
    element: "Earth",
    templeSpace: "Holy of Holies",
    storyStage: "Falling Action",
    dimension: "2 Presence",
    fractalGate: "Integration",
    spiritualFrequency: "Mirror Tone",
    bookColor: "Green",
    tribe: null,
    prophet: "David",
    apostle: "Matthew",
    directionalMapping: null,
  },
  {
    chapterNumber: 20,
    bookNumber: 4,
    divineName: "Final Heh",
    bookName: "Becoming Embodied",
    bookTheme: "Walking in Wisdom, Spirit, and Glory",
    chapterTitle: "The Body of Christ: Flesh Made Flame",
    geometryIcon: "Flower of Life",
    stone: "Beryl (2)",
    element: "Earth",
    templeSpace: "Holy of Holies",
    storyStage: "Resolution",
    dimension: "7 Name",
    fractalGate: "Hidden (West)",
    spiritualFrequency: "Radiant Bloom",
    bookColor: "Green",
    tribe: null,
    prophet: "Isaiah",
    apostle: "Thomas",
    directionalMapping: "West",
  },
  {
    chapterNumber: 21,
    bookNumber: 5,
    divineName: "YESHUA",
    bookName: "The Pattern Manifesto",
    bookTheme: "Jesus, the Fractal Fulfillment, and the Apostolic Flame",
    chapterTitle: "Yeshua: The Embodiment of YHWH",
    geometryIcon: "Star of David",
    stone: "Topaz (2)",
    element: "Plasma",
    templeSpace: "Ark",
    storyStage: "Exposition",
    dimension: "7 Name",
    fractalGate: "Revelation",
    spiritualFrequency: "Incarnational Wave",
    bookColor: "Gold/White",
    tribe: null,
    prophet: "Jeremiah",
    apostle: "James (Alphaeus)",
    directionalMapping: null,
  },
  {
    chapterNumber: 22,
    bookNumber: 5,
    divineName: "YESHUA",
    bookName: "The Pattern Manifesto",
    bookTheme: "Jesus, the Fractal Fulfillment, and the Apostolic Flame",
    chapterTitle: "The Spiral and the Sword: Jesus as Pattern and Portal",
    geometryIcon: "Fibonacci Circle",
    stone: "Chrysoprase",
    element: "Plasma",
    templeSpace: "Ark",
    storyStage: "Rising Action",
    dimension: "6 Image",
    fractalGate: "Internalization",
    spiritualFrequency: "Sword Spiral Resonance",
    bookColor: "Gold/White",
    tribe: null,
    prophet: "Ezekiel",
    apostle: "Thaddeus",
    directionalMapping: null,
  },
  {
    chapterNumber: 23,
    bookNumber: 5,
    divineName: "YESHUA",
    bookName: "The Pattern Manifesto",
    bookTheme: "Jesus, the Fractal Fulfillment, and the Apostolic Flame",
    chapterTitle: "The Name and the Nations: Fractal Mission in the Latter Days",
    geometryIcon: "Torus (3D)",
    stone: "Jacinth",
    element: "Plasma",
    templeSpace: "Ark",
    storyStage: "Climax",
    dimension: "4 Word",
    fractalGate: "Embodiment",
    spiritualFrequency: "Global Pulse",
    bookColor: "Gold/White",
    tribe: null,
    prophet: "Daniel",
    apostle: "Simon the Zealot",
    directionalMapping: null,
  },
  {
    chapterNumber: 24,
    bookNumber: 5,
    divineName: "YESHUA",
    bookName: "The Pattern Manifesto",
    bookTheme: "Jesus, the Fractal Fulfillment, and the Apostolic Flame",
    chapterTitle: "Pentecost, Fire, and the Echo of Eden",
    geometryIcon: "64 Star Tetrahedron",
    stone: "Amethyst (2)",
    element: "Plasma",
    templeSpace: "Ark",
    storyStage: "Falling Action",
    dimension: "7 Name",
    fractalGate: "Integration",
    spiritualFrequency: "Covenant Flame Ring",
    bookColor: "Gold/White",
    tribe: null,
    prophet: "Moses",
    apostle: "Matthias",
    directionalMapping: null,
  },
  {
    chapterNumber: 25,
    bookNumber: 5,
    divineName: "YESHUA",
    bookName: "The Pattern Manifesto",
    bookTheme: "Jesus, the Fractal Fulfillment, and the Apostolic Flame",
    chapterTitle: "The Commissioning Pattern: Jesus and the Sending of the Flame",
    geometryIcon: "Nested Fib Circles",
    stone: "White Sapphire",
    element: "Plasma",
    templeSpace: "Ark",
    storyStage: "Resolution",
    dimension: "7 Name",
    fractalGate: "Hidden (Center)",
    spiritualFrequency: "Shofar commission Resonance",
    bookColor: "Gold/White",
    tribe: null,
    prophet: "Jesus Christ",
    apostle: "Jesus Christ",
    directionalMapping: "Center",
  },
  {
    chapterNumber: 26,
    bookNumber: 5,
    divineName: "YESHUA",
    bookName: "The Pattern Manifesto",
    bookTheme: "Jesus, the Fractal Fulfillment, and the Apostolic Flame",
    chapterTitle: "The Apostolic Flame: Paul and the Global Replication Pattern",
    geometryIcon: "Fractal Network",
    stone: "Amethyst (3)",
    element: "Plasma",
    templeSpace: "Ark",
    storyStage: "Rising Action",
    dimension: "7 Name",
    fractalGate: "Revelation",
    spiritualFrequency: "Global Pulse",
    bookColor: "Gold/White",
    tribe: null,
    prophet: "Paul",
    apostle: "Paul",
    directionalMapping: "Global",
  }
];